<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'KryuuFileRepository\Module'                       => __DIR__ . '/Module.php',
  'KryuuFileRepository\Controller\FileController'    => __DIR__ . '/src/KryuuFileRepository/Controller/FileController.php',
  'KryuuFileRepository\Entity\File'                  => __DIR__ . '/src/KryuuFileRepository/Entity/File.php',
  'KryuuFileRepository\Entity\Keyword'               => __DIR__ . '/src/KryuuFileRepository/Entity/Keyword.php',
  'KryuuFileRepository\Exception\ExceptionInterface' => __DIR__ . '/src/KryuuFileRepository/Exception/ExceptionInterface.php',
  'KryuuFileRepository\Exception\RuntimeException'   => __DIR__ . '/src/KryuuFileRepository/Exception/RuntimeException.php',
  'KryuuFileRepository\Manager'                      => __DIR__ . '/src/KryuuFileRepository/Manager.php',
  'KryuuFileRepository\Service\Factory'              => __DIR__ . '/src/KryuuFileRepository/Service/Factory.php',
  'KryuuFileRepository\Version'                      => __DIR__ . '/src/KryuuFileRepository/Version.php',
  'KryuuFileRepository\View\Helper\KryuuFileRepository'         => __DIR__ . '/src/KryuuFileRepository/View/Helper/KryuuFileRepository.php',
);
