<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FileRepository\Module'                       => __DIR__ . '/Module.php',
  'FileRepository\Controller\FileController'    => __DIR__ . '/src/FileRepository/Controller/FileController.php',
  'FileRepository\Entity\File'                  => __DIR__ . '/src/FileRepository/Entity/File.php',
  'FileRepository\Entity\Keyword'               => __DIR__ . '/src/FileRepository/Entity/Keyword.php',
  'FileRepository\Exception\ExceptionInterface' => __DIR__ . '/src/FileRepository/Exception/ExceptionInterface.php',
  'FileRepository\Exception\RuntimeException'   => __DIR__ . '/src/FileRepository/Exception/RuntimeException.php',
  'FileRepository\Manager'                      => __DIR__ . '/src/FileRepository/Manager.php',
  'FileRepository\Service\Factory'              => __DIR__ . '/src/FileRepository/Service/Factory.php',
  'FileRepository\Version'                      => __DIR__ . '/src/FileRepository/Version.php',
  'FileRepository\View\Helper\FileRepository'         => __DIR__ . '/src/FileRepository/View/Helper/FileRepository.php',
);
